### ISSUE TITLE
Determining file type from contents rather than name

### ISSUE THREAD

**Issue by nickilott** [marcelm/dnaio#1]
Hi, I have been trying to run trim_galore on fastq files with naming like *.fastq.1.gz. However there is an error which seems to relate to identifying the file type from the contents i.e.

>>> import dnaio
>>> f = dnaio.open("13714_1#1.fastq.2.gz")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<path>/python3.6/site-packages/dnaio/__init__.py", line 83, in open
    file1, fileformat=fileformat, mode=mode, qualities=qualities)
  File "/<path>/python3.6/site-packages/dnaio/__init__.py", line 148, in _open_single
    if file.seekable():
AttributeError: 'PipedGzipReader' object has no attribute 'seekable'

**Comment by marcelm** [comment]
Thanks! This was an oversight in the xopen library, where I recently changed how gzipped files are read. I have fixed this now in https://github.com/marcelm/xopen/commit/aa905e14537ef2b908197f059b044dd7942f4794 . Please update to xopen 0.7.1 to get the fix (should be on PyPI in a couple of minutes) (`pip install --upgrade xopen`).
