### ISSUE TITLE
ResourceWarnings

### ISSUE THREAD

**Issue by marcelm** [marcelm/dnaio#103]
When running the tests, there are 12 ResourceWarnings. Showing just one of them:
```
$ python -X dev -X tracemalloc -m pytest
[...]
tests/test_open.py::test_paired_open_with_multiple_args[fasta-r-PairedEndReader]
  .../dnaio/.venv/lib/python3.10/site-packages/_pytest/python.py:192: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-marcel/pytest-191/test_paired_open_with_multiple0/file' encoding='UTF-8'>
    result = testfunction(**testargs)
  
  Object allocated at:
    File ".../dnaio/.venv/lib/python3.10/site-packages/_pytest/python.py", line 192
      result = testfunction(**testargs)
[...]
```
I don’t have time at the moment right now to fix this, so just filing an issue. I would like to at least know what is going on before releasing 0.10.

These warnings were not there in v0.9.1.

**Comment by rhpvorderman** [comment]
That's odd. I willl have a look.

**Comment by rhpvorderman** [comment]
Fixed and pushed to main: https://github.com/marcelm/dnaio/commit/316dc02ab0a0538e841bf857478d93cb0eb4c464

Files were not closed in the tests. So I used a context manager and the issue was gone.

**Comment by marcelm** [comment]
Thanks! That commit fixes it for me.
