### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/dnaio#114]
Given #110 warrants a new release as you say, I think we should name it 1.0.0. it is a stable library which has been used in production for years. Easily the best and one of the most feature rich parsers out there.. See also https://0ver.org

**Comment by marcelm** [comment]
I don’t know whether I stated that explicitly anywhere, but last year the idea was that we release 1.0 when we have a paper out. Since that probably isn’t going to happen any time soon (I’m still interested, but other things always appear to be more urgent), it’s fine to release 1.0.0 now. I agree the library is stable enough to warrant this.

**Comment by marcelm** [comment]
I pushed the `v1.0.0` tag.

**Comment by rhpvorderman** [comment]
> I don’t know whether I stated that explicitly anywhere, but last year the idea was that we release 1.0 when we have a paper out. 

Oops, I can't seem to remember. Sorry for that. 

>Since that probably isn’t going to happen any time soon (I’m still interested, but other things always appear to be more urgent),

Yes I am also sorry for that. Our clinical genetics department is switching to the DRAGEN caller as well as a new variant analysis provider and I am needed quite a lot for dedicated bioinformatics support to get that all up. I currently have a lot of tasks going on. On top of that, I find that my new sequence quality tool (which started as a thought-experiment to see how much faster than FastQC I could do the QC) has quite rapidly grown into something very useful also for long read sequencing. So my programming time tends to go into that tool. I am getting feedback from our in-house sequencing center on it. Very nice to work on, but that means that pushing the dnaio paper has been getting a lot less priority. 
 
Maybe I can talk to my manager to dedicate some time on the paper but it is going to have to wait a few months I am affraid with all that is going on.
