### ISSUE TITLE
_Py_NegativeRefcount error

### ISSUE THREAD

**Issue by bistace** [marcelm/dnaio#132]
Hello and thank you for developping dnaio.

I am trying to use it but I am getting an error:
```text
./Include/object.h:602: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x7f11cc6fe660 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: finalizing (tstate=0x00007f11d4f08a78)
 
Current thread 0x00007f11d5143740 (most recent call first):
  <no Python frame>
Abandon (core dumped)
```

Our Python is compiled with debug options so not a lot of users will see this error but it is hidden and still occuring when not using assertions. To reproduce this error, a simple script like this one will work:
```python
import dnaio
print("Test")
```

Would you be willing to take a look at this?

**Comment by rhpvorderman** [comment]
I tested a few versions and this goes back to 0.7.0. Which is not good. 

I suspect Cython is to blame though if things go badly at module initialization... But no, I tested on a branch that is exclusively in C (I wanted to see what Cython's overhead is) and that throws the same error. This is very puzzling.

**Comment by rhpvorderman** [comment]
I pinpointed this to an issue in zlib_ng
It is not a dnaio issue

**Comment by bistace** [comment]
Very nice, thanks a lot for fixing this!

**Comment by bistace** [comment]
Hi, 
we just tested and everything seems to work flawlessly, thank you!

**Comment by rhpvorderman** [comment]
Thank you for reporting back!
