### ISSUE TITLE
Update bioconda-recipe to support osx-arm64

### ISSUE THREAD

**Issue by isaacovercast** [marcelm/dnaio#137]
<You might recognize this issue from the cutadapt repo ;p>

The bioconda folks [recently rolled out support for osx-arm64 builds](https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2221176852) (Mac M1/M2). Enabling the build for this platform is currently 'opt-in' so you have to add a flag to the meta.yaml (documented at the link). I have updated my own package following this direction and it works fine.

**Comment by marcelm** [comment]
Yes! Let’s continue discussion on the Cutadapt issue or on the Bioconda tracker; I’ll close this issue.
