### ISSUE TITLE
Fastq_iter improvements

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/dnaio#25]
Hi, I have made quite some PRs in the last week and I have still some plans, so I put them here so that the PRs do not come out of the blue.

Planned PRs:
- [ ] Improve the paired FASTQ iteration by moving it into _core.pyx. I found that `record_names_match` takes 40 ns. Which is quite good. Then I benchmarked a Python function that returns `True`. Also 40 ns... A Cython function that returns `True` 28 ns. So of the 40 ns there is 28 ns call overhead. This is bad because iterating over two paired FASTQ files takes about 40% longer than iterating over two FASTQ files individually. This is bad because `zip` and `zip_longest` by themselves have very little overhead. By moving the loop into Cython a lot of checks in the loop 
- [ ] Add behaviour that recognizes `sequence_class=tuple` and simply yields a tuple. `yield name, sequence, qualities`. This is 10% faster than yielding Sequence types. This is quite nice if the rich interface of Sequence is not needed.
- [ ] Add a binary mode. Enabled with `dnaio.open(file, mode="rb")`. This uses PyBytes_FromStringAndSize internally instead of PyUnicode_DecodeLatin1. This improves speed by more than 20%.
- [ ] Replace PyUnicode_DecodeLatin1 with PyUnicode_DecodeASCII for sequence and qualities. PyUnicode_DecodeLatin1 has already a tremendous overhead compared to PyBytes_FromStringAndSize. (1100ms vs 850ms for parsing respectively), and the only added benefit is that it returns a string. By using PyUnicode_DecodeASCII for sequence and qualities, all sequence and qualities characters are tested for not exceeding 128. Since these are all invalid sequence and quality chars this is a value add. This does cost however, and parsing is a little slower (1200) ms. Given the tremendous speed improvements thank to memchr, I reckon there is room for a little quality of life improvement on the string side.

**Comment by marcelm** [comment]
Hi, thanks for the overview. I have a deadline coming up and then of course the holidays are soon, so I would like (and need) to take a break. Perhaps we can get #15 merged within the next couple of days, but I’ll have to ignore anything else for now. I realize this may not be so satisfactory now that you are on a roll.

**Comment by rhpvorderman** [comment]
Dear @marcelm , take all the rest you need. The PRs are not time-critical. I can only make use of them after dnaio is released anyway.

Dnaio is already the fastest FASTQ parser out there. It is a great project, and I have learned much from it. Thank you for that. Also I found that diving deeper into this was a great way to learn more about the C standard library and Python's C-API functions. This was fun and useful. I think this project is very interesting so I have been also hacking at it in my spare time. Just to see what the effect of some choices would be. I fully understand that you could not possibly keep up with al the PRs coming so fast. 

Most times you review a PR of me you make an insightful comment that learns me something new, or further cements my understanding of things. It leads to better code always. It is always a pleasure working with you, and I value that cooperation much more than speedy merging. Thank you for working with me, and thank you for the trust that you give me by making me co-maintainer on you projects.

Have a nice holiday!

**Comment by marcelm** [comment]
Hi, is it ok if I make a release this week? I cannot review #30 at the moment, but want to make the Windows-compatible dnaio version available. And having the speed improvements available in a release would also be nice.

**Comment by rhpvorderman** [comment]
Yes, of course! #30 is quite extensive so that can be in a next release.

**Comment by rhpvorderman** [comment]
I think most of this issues are adressed or have their own more clear dedicated issues now.
