### ISSUE TITLE
Consider renaming Sequence to SequenceRecord

### ISSUE THREAD

**Issue by marcelm** [marcelm/dnaio#36]
This has bothered me for a long time: A `Sequence` isn’t actually just a sequence; it is an object containing a sequence of nucleotides, a sequence of quality values and a name. The misnaming becomes obvious when one considers that a `Sequence` has a `sequence` attribute, so I’m sometimes tempted to write something like `s = sequence.sequence` or similar.

Biopython has `SeqRecord`, but I don’t like abbreviations in class names and to reduce the risk of being confusing with the Biopython class, I think it should be `SequenceRecord`.

**Comment by rhpvorderman** [comment]
Sure. In Pybam the BAM record is called BamRecord. This does not even have to backwards-incompatible, as we can simply add in a deprecated type alias.
