### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by marcelm** [marcelm/dnaio#56]
Here are a couple of things I noticed should possibly be revised before releasing a version 1.0. I’ll extend this when I find more.

* `SequenceRecord.fastq_bytes_two_headers()` is redundant with `SequenceRecord.fastq_bytes(two_headers=True)`
* `record_names_match` and `record_names_match_bytes` should possibly be renamed to `record_ids_match` and `record_ids_match_bytes` because those names are more accurate (also requires that the C-level `record_ids_match` is renamed)

**Comment by rhpvorderman** [comment]
Agreed and agreed.
fastq_bytes_two_headers is a very ugly method name, so it would be nice to get rid of that.

As regards to the record_names_match etc. These functions have been made completely redundant by the `is_mate` methods. Given that these functions make no sense outside of a FASTQ or FASTA record context, wouldn't it be best to remove them entirely?

**Comment by marcelm** [comment]
> Given that these functions make no sense outside of a FASTQ or FASTA record context, wouldn't it be best to remove them entirely?

I would like to leave them in, but hide them (remove them from `__all__` and the documentation) because Cutadapt uses them at the moment and does not upper-bound its dnaio dependency, so any install will always get the most recent one. If the next dnaio release doesn’t have the functions, Cutadapt breaks. Even when I fix Cutadapt, older versions will still have that problem and I find it quite possible that folks install older Cutadapt versions on purpose to be certain they get specific behavior.

Also, since there’s no dnaio release with `.is_mate()`, yet, I cannot even port the current Cutadapt version at the moment.

But in any case: With that in mind, renaming these functions doesn’t make sense.

> EDIT: That would require a Major Version Change. But I feel dnaio is quite ready for 1.0.0!

I want to have better documentation before that, but yes, it’s ready feature-wise.

**Comment by rhpvorderman** [comment]
> I would like to leave them in, but hide them (remove them from __all__ and the documentation) because Cutadapt uses them at the moment and does not upper-bound its dnaio dependency, so any install will always get the most recent one.

Ah, I didn't consider that. I thought that cutadapt would have used the PairedEndReader objects. But in any case, it does make sense not to break backwards compatibility so rigourously if that is not needed.

Also our test suite uses the record_names_match functions to thoroughly test the underlying C function, and it would be quite some work to port that over to SequenceRecord.is_mate(other).

**Comment by marcelm** [comment]
> I thought that cutadapt would have used the PairedEndReader objects.

It’s only used in the code for `--rename` to check whether paired-end reads still have matching IDs after they have been renamed.
