### ISSUE TITLE
Remove BytesSequenceRecord

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/dnaio#66]
When I put BytesSequenceRecord in there were two major reasons:

- PyBytes_FromStringAndSize was much faster than PyUnicode_DecodeASCII
- Retrieving pointers from strings was deemed difficult, as strings do not have the buffer protocol.

I think both issues are now gone.

- ASCII checking the entire buffer and then using PyUnicode_New(..., 127) is only slightly slower than PyBytes_FromStringAndSize. (!0%) 
- Retrieving pointers from strings can be done very fast with PyUnicode_DATA. Since SequenceRecord ensures that strings can never be anything else than ASCII this is as fast as PyBytes_AS_STRING. 

On top of that, strings are more useful than bytes. Names should be strings. Sequences of nucleotides work more intuitive as strings. And qualities, are phred scores. These are an ASCII representation of the proper score and thus  work best as strings.

I was working on #65  when I realised that BytesSequenceRecord is now just a maintenance burden at this point.

**Comment by marcelm** [comment]
I’m glad this can be dropped. It’s good you noticed this before 1.0! This will also simplify the documentation a bit.

**Comment by rhpvorderman** [comment]
Glad you agree. In retrospect I should never have put it there, but there we go. "Voortschrijdend inzicht" as it is called in Dutch.
